name = "CoherentNoiseViewer"
uuid = "839173cb-aead-4daa-b806-4df9806a5dfe"
authors = ["Michael Fiano <mail@mfiano.net> and contributors"]
version = "0.1.0"

[deps]
CoherentNoise = "3547b4d8-3bdb-4c10-a099-d01a31e852e0"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
GLMakie = "0.6, 0.7"
Revise = "3.4"
julia = "1.6"
